name: vc-eval
channels:
  - conda-forge
  - bioconda
dependencies:
  - ncbi-genome-download
  - mason=2.0.9 
  - snakemake-minimal=7
  - python=3.10
  - pysam=0.22
  - dnaio
  - bwa=0.7.19
  - samtools
  - cmake=3.27
  - cxx-compiler
  - seaborn
  - minimap2=2.30
  - isa-l
  - pyyaml
  - bcftools
