# SLURM profile to be used with 'snakemake --profile=slurm'

cluster-sidecar: "slurm-sidecar.py"
cluster-cancel: "scancel"
restart-times: "0"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: "10"
max-status-checks-per-second: "10"
local-cores: 1
latency-wait: "5"
use-conda: "True"
use-singularity: "False"
jobs: "500"
printshellcmds: "True"

default-resources:
  runtime: 240
  mem_mb: 12000
  # account and partition should be specified in in settings.json

set-resources:
  single_end_truth:
    runtime: 10
    mem_mb: 2000

  mason_variator:
    mem_mb: 16000
    runtime: 720

  mason_simulate_reads:
    mem_mb: 96000
    runtime: 2880

  sim0:
    runtime: 600

  ccs:
    mem_mb: 32000

  bwa_mem_index:
    mem_mb: 48000
    runtime: 360

  compile_strobealign:
    mem_mb: 8000

  bam_accuracy:
    mem_mb: 2000
    runtime: 30

  paf_accuracy:
    mem_mb: 2000
    runtime: 30

  bwa_mem_paired_end:
    mem_mb: 32000

  bwa_mem_align:
    mem_mb: 40000
    runtime: 480

  minimap2_index:
    mem_mb: 64000

  minimap2_align:
    mem_mb: 40000
    runtime: 480

  minimap2_paf_single_end:
    mem_mb: 24000

  minimap2_paired_end:
    mem_mb: 24000

  minimap2_single_end:
    mem_mb: 24000

  xmapper_paired_end:
    mem_mb: 32000
    runtime: 120

  xmapper_single_end:
    mem_mb: 32000
    runtime: 120

  bcftools_norm:
    mem_mb: 36000
    runtime: 480

  bcftools_mpileup:
    mem_mb: 16000
    runtime: 720

  strobealign:
    mem_mb: 48000
    runtime: 120

  bcftools_call:
    mem_mb: 48000
    runtime: 360

  make_sorted_bam:
    mem_mb: 36000
    runtime: 300

set-threads:
#  my-example-rule: 10
